// Mock data for the HealthCare+ hospital appointment system.

export const heroImage =
  "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080";

export const adminBuildingImage =
  "https://images.unsplash.com/photo-1631217871099-88310a909a32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080";

const p = (n: number) => "";

export interface Doctor {
  id: string;
  name: string;
  specialization: string;
  hospital: string;
  experience: number;
  fee: number;
  rating: number;
  reviews: number;
  availableToday: boolean;
  status?: string;
  photo: string;
  qualifications: string;
  languages: string[];
  about: string;
  department: string;
}

export const specializations = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Gynecology",
  "Psychiatry",
  "General Medicine",
  "ENT",
  "Ophthalmology",
  "Gastroenterology",
  "Endocrinology",
  "Pulmonology",
  "Urology",
  "Oncology",
  "Rheumatology",
];
export const timeSlots = {
  Morning: ["09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM"],
  Afternoon: ["12:00 PM", "12:30 PM", "02:00 PM", "02:30 PM", "03:00 PM"],
  Evening: ["05:00 PM", "05:30 PM", "06:00 PM", "06:30 PM", "07:00 PM"],
};

export type AppointmentStatus = "Upcoming" | "Completed" | "Cancelled" | "Pending" | "Approved";

export const doctors: Doctor[] = [
  {
    id: "d57",
    name: "Dr. Bhavani E",
    specialization: "Pediatrics",
    hospital: "BhavaniKids Clinic",
    experience: 10,
    fee: 850,
    rating: 4.7,
    reviews: 198,
    availableToday: true,
    photo: p(16),
    qualifications: "MBBS, DCH",
    languages: ["English", "Tamil"],
    about: "Dr. Bhavani E is a caring pediatrician specializing in infant care, immunization schedules, growth monitoring and childhood illness management.",
    department: "Pediatrics",
  },
  {
    id: "d58",
    name: "Dr. Nikhila Sharma",
    specialization: "General Medicine",
    hospital: "NikhilaHealth Clinic",
    experience: 8,
    fee: 700,
    rating: 4.6,
    reviews: 234,
    availableToday: false,
    photo: p(17),
    qualifications: "BSc, MBBS",
    languages: ["English", "Tamil", "Hindi"],
    about: "Dr. Nikhila Sharma offers holistic primary care consultations covering routine checkups, acute illness and chronic disease monitoring.",
    department: "General Medicine",
  },
  {
    id: "d59",
    name: "Dr. Niraanjan S R",
    specialization: "Gynecology",
    hospital: "MothersFirst Clinic",
    experience: 12,
    fee: 1050,
    rating: 4.7,
    reviews: 221,
    availableToday: true,
    photo: p(18),
    qualifications: "MBBS, DGO",
    languages: ["English", "Tamil"],
    about: "Dr. Niraanjan S R specializes in obstetric care, high-risk pregnancies and gynecological procedures at MothersFirst Clinic.",
    department: "Gynecology",
  },
  {
    id: "d60",
    name: "Dr. Latha V",
    specialization: "Gynecology",
    hospital: "WomenCare Clinic",
    experience: 15,
    fee: 1100,
    rating: 4.8,
    reviews: 267,
    availableToday: false,
    photo: p(19),
    qualifications: "MBBS, DGO",
    languages: ["English", "Tamil"],
    about: "Dr. Latha V has 15 years of experience in obstetrics, fertility counselling, PCOS management and minimally invasive gynecology.",
    department: "Gynecology",
  },
  {
    id: "d61",
    name: "Dr. Lavanya Nagajothi",
    specialization: "Endocrinology",
    hospital: "ThyroidCare Clinic",
    experience: 11,
    fee: 1150,
    rating: 4.7,
    reviews: 189,
    availableToday: true,
    photo: p(20),
    qualifications: "MBBS, FAIMS, MRCH",
    languages: ["English", "Tamil"],
    about: "Dr. Lavanya Nagajothi focuses on thyroid disorders, diabetes, metabolic syndrome and hormonal health with a comprehensive clinical approach.",
    department: "Endocrinology",
  },
  {
    id: "d62",
    name: "Dr. Durai P",
    specialization: "General Medicine",
    hospital: "DuraiClinic",
    experience: 9,
    fee: 680,
    rating: 4.6,
    reviews: 201,
    availableToday: true,
    photo: p(21),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Durai P is a general physician known for thorough evaluations and patient-friendly consultations for everyday health concerns.",
    department: "General Medicine",
  },
  {
    id: "d63",
    name: "Dr. Chitra Jothinathan",
    specialization: "General Medicine",
    hospital: "ChitraSurgical Clinic",
    experience: 14,
    fee: 900,
    rating: 4.7,
    reviews: 198,
    availableToday: false,
    photo: p(22),
    qualifications: "MS, DLS, FMAS",
    languages: ["English", "Tamil"],
    about: "Dr. Chitra Jothinathan is a surgeon offering laparoscopic general surgery including cholecystectomy, appendectomy and hernia repair.",
    department: "General Medicine",
  },
  {
    id: "d64",
    name: "Dr. Jothinathan K",
    specialization: "Gynecology",
    hospital: "JothiWomen's Clinic",
    experience: 16,
    fee: 1100,
    rating: 4.8,
    reviews: 234,
    availableToday: true,
    photo: p(23),
    qualifications: "MD, DGO",
    languages: ["English", "Tamil"],
    about: "Dr. Jothinathan K is a respected obstetrician and gynaecologist managing complex deliveries, uterine conditions and gynecological cancers.",
    department: "Gynecology",
  },
  {
    id: "d65",
    name: "Dr. Usha Vardrajan",
    specialization: "Gynecology",
    hospital: "UshaMaternity Clinic",
    experience: 20,
    fee: 1200,
    rating: 4.9,
    reviews: 312,
    availableToday: false,
    photo: p(24),
    qualifications: "FRCOG",
    languages: ["English", "Tamil"],
    about: "Dr. Usha Vardrajan is a Fellow of the Royal College of Obstetricians and Gynaecologists with two decades of experience in women's health and high-risk obstetrics.",
    department: "Gynecology",
  },
  {
    id: "d66",
    name: "Dr. Manu Lakshmi",
    specialization: "Urology",
    hospital: "UroLife Clinic",
    experience: 15,
    fee: 1400,
    rating: 4.8,
    reviews: 198,
    availableToday: true,
    photo: p(25),
    qualifications: "MS, MCh (Urology)",
    languages: ["English", "Tamil"],
    about: "Dr. Manu Lakshmi is a urologist specializing in kidney stones, bladder conditions, prostate disorders and endoscopic urological surgery.",
    department: "Urology",
  },
  {
    id: "d67",
    name: "Dr. Karthick Gunasekaran",
    specialization: "Gastroenterology",
    hospital: "Narayana Health, Chennai",
    experience: 17,
    fee: 1300,
    rating: 4.8,
    reviews: 234,
    availableToday: false,
    photo: p(26),
    qualifications: "MD, DCH, DM (Pediatric Gastroenterology)",
    languages: ["English", "Tamil"],
    about: "Dr. Karthick Gunasekaran is a pediatric gastroenterologist at Narayana Health managing liver diseases, IBD and complex digestive disorders in children.",
    department: "Gastroenterology",
  },
  {
    id: "d68",
    name: "Dr. Srinivas S",
    specialization: "General Medicine",
    hospital: "SrinivasClinic",
    experience: 11,
    fee: 700,
    rating: 4.6,
    reviews: 198,
    availableToday: true,
    photo: p(27),
    qualifications: "MS, DGO",
    languages: ["English", "Tamil", "Telugu"],
    about: "Dr. Srinivas S provides reliable general outpatient care with a special focus on nutritional health and lifestyle modification.",
    department: "General Medicine",
  },
  {
    id: "d69",
    name: "Dr. Sudha Jeyakumar S",
    specialization: "Gynecology",
    hospital: "SudhaWomen's Clinic",
    experience: 13,
    fee: 1100,
    rating: 4.7,
    reviews: 221,
    availableToday: true,
    photo: p(28),
    qualifications: "MD, Gyn",
    languages: ["English", "Tamil"],
    about: "Dr. Sudha Jeyakumar S specializes in antenatal care, normal and caesarean deliveries, and post-natal care for mothers and newborns.",
    department: "Gynecology",
  },
  {
    id: "d70",
    name: "Dr. Siva Prasad K",
    specialization: "General Medicine",
    hospital: "SivaClinic",
    experience: 10,
    fee: 700,
    rating: 4.6,
    reviews: 189,
    availableToday: false,
    photo: p(29),
    qualifications: "MD",
    languages: ["English", "Tamil", "Telugu"],
    about: "Dr. Siva Prasad K is a general physician providing broad-spectrum medical care including chronic disease management and acute care.",
    department: "General Medicine",
  },
  {
    id: "d71",
    name: "Dr. Swaminathan G",
    specialization: "Gynecology",
    hospital: "SwaminathanClinic",
    experience: 12,
    fee: 1050,
    rating: 4.7,
    reviews: 213,
    availableToday: true,
    photo: p(30),
    qualifications: "MBBS, DGO",
    languages: ["English", "Tamil"],
    about: "Dr. Swaminathan G offers compassionate obstetric and gynaecological services including antenatal consultations and laparoscopic procedures.",
    department: "Gynecology",
  },
  {
    id: "d72",
    name: "Dr. Pushpa Balasubramanyam",
    specialization: "Orthopedics",
    hospital: "BoneAlign Clinic",
    experience: 14,
    fee: 1200,
    rating: 4.7,
    reviews: 201,
    availableToday: false,
    photo: p(31),
    qualifications: "MBBS, MD (Orthopedics)",
    languages: ["English", "Tamil"],
    about: "Dr. Pushpa Balasubramanyam manages musculoskeletal injuries, joint pain, fractures and performs orthopedic surgical procedures.",
    department: "Orthopedics",
  },
  {
    id: "d73",
    name: "Dr. Chokkalingam",
    specialization: "Gynecology",
    hospital: "ChokkaliClinic",
    experience: 11,
    fee: 1000,
    rating: 4.7,
    reviews: 187,
    availableToday: true,
    photo: p(32),
    qualifications: "MBBS, MD, DM (Gynaecology)",
    languages: ["English", "Tamil"],
    about: "Dr. Chokkalingam is a gynaecologist with clinical expertise in fertility treatments, uterine disorders and postmenopausal care.",
    department: "Gynecology",
  },
  {
    id: "d74",
    name: "Dr. Roshini Rohit",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 8,
    fee: 750,
    rating: 4.6,
    reviews: 213,
    availableToday: false,
    photo: p(33),
    qualifications: "MBBS",
    languages: ["English", "Tamil", "Hindi"],
    about: "Dr. Roshini Rohit is a general physician at Narayana Health, Chennai, committed to providing quality primary and preventive health care.",
    department: "General Medicine",
  },
  {
    id: "d75",
    name: "Dr. Nivetha",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 7,
    fee: 720,
    rating: 4.5,
    reviews: 178,
    availableToday: true,
    photo: p(34),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Nivetha is an enthusiastic young physician at Narayana Health dedicated to delivering empathetic and evidence-based outpatient care.",
    department: "General Medicine",
  },
  {
    id: "d76",
    name: "Dr. Sampath Kumar",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 12,
    fee: 780,
    rating: 4.6,
    reviews: 234,
    availableToday: true,
    photo: p(35),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Sampath Kumar manages fever, infections, metabolic disorders and acute conditions at Narayana Health, Chennai.",
    department: "General Medicine",
  },
  {
    id: "d77",
    name: "Dr. Vijaya Ragavan K",
    specialization: "Pediatrics",
    hospital: "VijayaKids Clinic",
    experience: 13,
    fee: 900,
    rating: 4.7,
    reviews: 213,
    availableToday: false,
    photo: p(36),
    qualifications: "MBBS, DCH, FMH",
    languages: ["English", "Tamil"],
    about: "Dr. Vijaya Ragavan K is a family-focused pediatrician providing well-child checkups, vaccination drives and management of acute childhood illnesses.",
    department: "Pediatrics",
  },
  {
    id: "d78",
    name: "Dr. Susovan Mitra",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 16,
    fee: 800,
    rating: 4.7,
    reviews: 267,
    availableToday: true,
    photo: p(37),
    qualifications: "MBBS",
    languages: ["English", "Tamil", "Bengali"],
    about: "Dr. Susovan Mitra is a general physician at Narayana Health, bringing multidisciplinary experience in internal medicine and complex disease management.",
    department: "General Medicine",
  },
  {
    id: "d79",
    name: "Dr. Gajendran T N",
    specialization: "General Medicine",
    hospital: "GajendraCare Clinic",
    experience: 14,
    fee: 750,
    rating: 4.7,
    reviews: 198,
    availableToday: false,
    photo: p(38),
    qualifications: "MBBS, ACLS, SCFHS",
    languages: ["English", "Tamil"],
    about: "Dr. Gajendran T N has international training credentials and specializes in diabetes management, emergency medicine and lifestyle disorders.",
    department: "General Medicine",
  },
  {
    id: "d80",
    name: "Dr. Meganathan R",
    specialization: "General Medicine",
    hospital: "MeganCare Clinic",
    experience: 10,
    fee: 700,
    rating: 4.6,
    reviews: 178,
    availableToday: true,
    photo: p(39),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Meganathan R offers dependable outpatient general medicine consultations with a patient-friendly approach and holistic care.",
    department: "General Medicine",
  },
  {
    id: "d81",
    name: "Dr. Hari K",
    specialization: "Endocrinology",
    hospital: "DiabetaHari Clinic",
    experience: 12,
    fee: 1100,
    rating: 4.7,
    reviews: 198,
    availableToday: false,
    photo: p(0),
    qualifications: "MBBS, F.Diab, CCEBDM",
    languages: ["English", "Tamil"],
    about: "Dr. Hari K is an accredited diabetologist managing Type 1, Type 2 and gestational diabetes with advanced insulin management protocols.",
    department: "Endocrinology",
  },
  {
    id: "d82",
    name: "Dr. Tamil Azhagan",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 15,
    fee: 800,
    rating: 4.7,
    reviews: 234,
    availableToday: true,
    photo: p(1),
    qualifications: "MBBS, MD, DM",
    languages: ["English", "Tamil"],
    about: "Dr. Tamil Azhagan is an experienced physician at Narayana Health with DM qualification, specializing in critical internal medicine and complex case management.",
    department: "General Medicine",
  },
  {
    id: "d83",
    name: "Dr. Mohamed Naazim",
    specialization: "ENT",
    hospital: "NaazimENT Clinic",
    experience: 13,
    fee: 950,
    rating: 4.8,
    reviews: 213,
    availableToday: true,
    photo: p(2),
    qualifications: "MBBS, MS (ENT)",
    languages: ["English", "Tamil", "Urdu"],
    about: "Dr. Mohamed Naazim is an ENT specialist managing hearing impairment, chronic sinusitis, voice disorders and nasal surgeries.",
    department: "ENT",
  },
  {
    id: "d84",
    name: "Dr. Raghuraman S",
    specialization: "Orthopedics",
    hospital: "RaghuBone Clinic",
    experience: 15,
    fee: 1200,
    rating: 4.7,
    reviews: 187,
    availableToday: false,
    photo: p(3),
    qualifications: "MBBS, MS (Orthopedics)",
    languages: ["English", "Tamil"],
    about: "Dr. Raghuraman S treats bone fractures, sports injuries, knee arthritis and performs arthroplasty and arthroscopic surgeries.",
    department: "Orthopedics",
  },
  {
    id: "d85",
    name: "Dr. K. N. Surya Prakash",
    specialization: "General Medicine",
    hospital: "Narayana Health, Chennai",
    experience: 12,
    fee: 800,
    rating: 4.7,
    reviews: 198,
    availableToday: true,
    photo: p(4),
    qualifications: "MD",
    languages: ["English", "Tamil", "Telugu"],
    about: "Dr. K. N. Surya Prakash is a dedicated physician at Narayana Health providing evidence-based care for chronic and acute medical conditions.",
    department: "General Medicine",
  },
  {
    id: "d86",
    name: "Dr. R. K. Bagdi",
    specialization: "Cardiology",
    hospital: "BagdiCardiac Clinic",
    experience: 16,
    fee: 1400,
    rating: 4.8,
    reviews: 234,
    availableToday: false,
    photo: p(5),
    qualifications: "MBBS, MD, DM (Cardiology)",
    languages: ["English", "Tamil", "Hindi"],
    about: "Dr. R. K. Bagdi is a cardiologist with expertise in cardiac imaging, heart failure management and interventional cardiology procedures.",
    department: "Cardiology",
  },
  {
    id: "d87",
    name: "Dr. Girithar",
    specialization: "General Medicine",
    hospital: "GiriCare Clinic",
    experience: 9,
    fee: 700,
    rating: 4.6,
    reviews: 198,
    availableToday: true,
    photo: p(6),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Girithar offers accessible and thorough general medicine consultations focusing on primary care, health screenings and chronic disease follow-up.",
    department: "General Medicine",
  },
  {
    id: "d88",
    name: "Dr. Ragumani",
    specialization: "General Medicine",
    hospital: "RaguClinic",
    experience: 11,
    fee: 720,
    rating: 4.6,
    reviews: 178,
    availableToday: false,
    photo: p(7),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Ragumani is a general physician and emergency medicine officer providing prompt care for medical emergencies and outpatient consultations.",
    department: "General Medicine",
  },
  {
    id: "d89",
    name: "Dr. Sadiya Fathima",
    specialization: "Orthopedics",
    hospital: "FatimaOrthoCare Clinic",
    experience: 10,
    fee: 1100,
    rating: 4.7,
    reviews: 187,
    availableToday: true,
    photo: p(8),
    qualifications: "MBBS, D.Ortho, FASIF",
    languages: ["English", "Tamil", "Urdu"],
    about: "Dr. Sadiya Fathima is an orthopedic surgeon specializing in trauma surgery, fracture management and sports-related musculoskeletal injuries.",
    department: "Orthopedics",
  },
  {
    id: "d90",
    name: "Dr. Ananth",
    specialization: "Pediatrics",
    hospital: "Narayana Health, Chennai",
    experience: 15,
    fee: 950,
    rating: 4.8,
    reviews: 234,
    availableToday: false,
    photo: p(9),
    qualifications: "MBBS, MS, MCh",
    languages: ["English", "Tamil"],
    about: "Dr. Ananth is a pediatric surgeon at Narayana Health handling congenital anomalies, pediatric trauma and complex neonatal surgical conditions.",
    department: "Pediatrics",
  },
  {
    id: "d91",
    name: "Dr. Subramaniam S",
    specialization: "General Medicine",
    hospital: "SubraSurgical Clinic",
    experience: 18,
    fee: 900,
    rating: 4.8,
    reviews: 267,
    availableToday: true,
    photo: p(10),
    qualifications: "MS (General Surgery)",
    languages: ["English", "Tamil"],
    about: "Dr. Subramaniam S is a senior general surgeon managing appendicitis, hernia, thyroid surgeries and abdominal emergencies.",
    department: "General Medicine",
  },
  {
    id: "d92",
    name: "Dr. Saravanan",
    specialization: "ENT",
    hospital: "SaraENT Clinic",
    experience: 12,
    fee: 950,
    rating: 4.7,
    reviews: 201,
    availableToday: true,
    photo: p(11),
    qualifications: "MBBS, DLO",
    languages: ["English", "Tamil"],
    about: "Dr. Saravanan is an ENT specialist skilled in managing ear wax impaction, chronic otitis media, nasal polyps and adenoid conditions.",
    department: "ENT",
  },
  {
    id: "d93",
    name: "Dr. Mangai Saravanan",
    specialization: "Endocrinology",
    hospital: "MangaiDiabetes Clinic",
    experience: 9,
    fee: 1100,
    rating: 4.7,
    reviews: 178,
    availableToday: false,
    photo: p(12),
    qualifications: "MBBS",
    languages: ["English", "Tamil"],
    about: "Dr. Mangai Saravanan provides diabetes education, insulin management and lifestyle counselling for patients with metabolic conditions.",
    department: "Endocrinology",
  },
  {
    id: "d94",
    name: "Dr. Shyam Sundar R",
    specialization: "ENT",
    hospital: "ShyamENT Clinic",
    experience: 14,
    fee: 950,
    rating: 4.8,
    reviews: 213,
    availableToday: true,
    photo: p(13),
    qualifications: "MBBS, DLO",
    languages: ["English", "Tamil", "Hindi"],
    about: "Dr. Shyam Sundar R is an ENT consultant treating vertigo, tinnitus, sinus infections, tonsillitis and conducting microear surgeries.",
    department: "ENT",
  },
  {
    id: "d95",
    name: "Dr. Tamil Selvan",
    specialization: "Cardiology",
    hospital: "TamilCardiac Clinic",
    experience: 16,
    fee: 1350,
    rating: 4.8,
    reviews: 234,
    availableToday: false,
    photo: p(14),
    qualifications: "MD, DM (Cardiology)",
    languages: ["English", "Tamil"],
    about: "Dr. Tamil Selvan is a DM cardiologist specializing in cardiac risk stratification, non-invasive cardiology and hypertension management.",
    department: "Cardiology",
  },
  {
    id: "d96",
    name: "Dr. Thirugyanam",
    specialization: "Orthopedics",
    hospital: "ThiruBone Clinic",
    experience: 13,
    fee: 1150,
    rating: 4.7,
    reviews: 198,
    availableToday: true,
    photo: p(15),
    qualifications: "MBBS, MS (Orthopedics)",
    languages: ["English", "Tamil"],
    about: "Dr. Thirugyanam treats complex orthopedic conditions including spinal deformities, hip dysplasia, joint replacement and fracture fixations.",
    department: "Orthopedics",
  },
  {
    id: "d97",
    name: "Dr. Sundar Kumar",
    specialization: "General Medicine",
    hospital: "SundarClinic",
    experience: 11,
    fee: 720,
    rating: 4.6,
    reviews: 213,
    availableToday: false,
    photo: p(16),
    qualifications: "MD",
    languages: ["English", "Tamil"],
    about: "Dr. Sundar Kumar is a general physician offering comprehensive outpatient care for hypertension, diabetes, fever and infectious diseases.",
    department: "General Medicine",
  },
  {
    id: "d98",
    name: "Dr. Ayaz Ahamed M",
    specialization: "Orthopedics",
    hospital: "Narayana Health, Chennai",
    experience: 14,
    fee: 1300,
    rating: 4.8,
    reviews: 234,
    availableToday: true,
    photo: p(17),
    qualifications: "MBBS, MS (Orthopedics)",
    languages: ["English", "Tamil", "Urdu"],
    about: "Dr. Ayaz Ahamed M is an orthopedic surgeon at Narayana Health performing joint replacements, trauma surgeries and arthroscopic procedures.",
    department: "Orthopedics",
  },
  {
    id: "d99",
    name: "Dr. Sajjad Hussain",
    specialization: "Cardiology",
    hospital: "Narayana Health, Chennai",
    experience: 18,
    fee: 1500,
    rating: 4.8,
    reviews: 267,
    availableToday: false,
    photo: p(18),
    qualifications: "MD",
    languages: ["English", "Tamil", "Urdu"],
    about: "Dr. Sajjad Hussain is a cardiologist at Narayana Health managing ischemic heart disease, cardiac arrhythmias and post-intervention rehabilitation.",
    department: "Cardiology",
  },
  {
    id: "d100",
    name: "Dr. Senthil Nathan J",
    specialization: "Cardiology",
    hospital: "SenthilCardiac Clinic",
    experience: 15,
    fee: 1350,
    rating: 4.8,
    reviews: 251,
    availableToday: true,
    photo: p(19),
    qualifications: "MBBS, MD (Cardiology)",
    languages: ["English", "Tamil"],
    about: "Dr. Senthil Nathan J is a cardiologist focused on preventive cardiology, echocardiography and managing complex coronary artery disease.",
    department: "Cardiology",
  },
];




export interface Patient {
  id: string;
  name: string;
  email: string;
  phone: string;
  appointments: number;
  status: "Active" | "Inactive";
  photo: string;
}

export const patients: Patient[] = [
  { id: "p1", name: "Mohanraj S.", email: "mohanraj@mail.com", phone: "+91 98765 43210", appointments: 12, status: "Active", photo: p(2) },
  { id: "p2", name: "Aisha Fernandes", email: "aisha.f@mail.com", phone: "+91 91234 56789", appointments: 5, status: "Active", photo: p(3) },
  { id: "p3", name: "Rohan Gupta", email: "rohan.g@mail.com", phone: "+91 99887 66554", appointments: 8, status: "Active", photo: p(0) },
  { id: "p4", name: "Neha Bansal", email: "neha.b@mail.com", phone: "+91 90000 12345", appointments: 2, status: "Inactive", photo: p(1) },
  { id: "p5", name: "David Miller", email: "david.m@mail.com", phone: "+91 93333 44455", appointments: 15, status: "Active", photo: p(6) },
  { id: "p6", name: "Sana Khan", email: "sana.k@mail.com", phone: "+91 94444 55566", appointments: 3, status: "Active", photo: p(5) },
];

// Chart data
export const appointmentsPerMonth = [
  { month: "Jan", appointments: 320 },
  { month: "Feb", appointments: 410 },
  { month: "Mar", appointments: 385 },
  { month: "Apr", appointments: 490 },
  { month: "May", appointments: 560 },
  { month: "Jun", appointments: 620 },
  { month: "Jul", appointments: 710 },
];

export const patientGrowth = [
  { month: "Jan", patients: 1200 },
  { month: "Feb", patients: 1650 },
  { month: "Mar", patients: 2100 },
  { month: "Apr", patients: 2900 },
  { month: "May", patients: 3800 },
  { month: "Jun", patients: 4600 },
  { month: "Jul", patients: 5400 },
];

export const departmentDistribution = [
  { name: "Cardiology", value: 28, color: "#2563eb" },
  { name: "Pediatrics", value: 22, color: "#14b8a6" },
  { name: "Orthopedics", value: 18, color: "#6366f1" },
  { name: "Dermatology", value: 16, color: "#f59e0b" },
  { name: "Others", value: 16, color: "#ec4899" },
];

export const doctorPerformance = [
  { name: "Dr. Sharma", patients: 320 },
  { name: "Dr. Iyer", patients: 290 },
  { name: "Dr. Nair", patients: 260 },
  { name: "Dr. Kapoor", patients: 210 },
  { name: "Dr. Menon", patients: 180 },
];

export const testimonials = [
  {
    id: "t1",
    name: "Priya Ramesh",
    role: "Mother of two, Chennai",
    photo: p(3),
    rating: 5,
    quote:
      "Booking was really quick. The doctor was kind and explained everything clearly. I will definitely use this again.",
  },
  {
    id: "t2",
    name: "James Anderson",
    role: "Software Engineer, Bangalore",
    photo: p(6),
    rating: 4,
    quote:
      "I use this to book appointments for my parents. The reminders are super helpful and booking is simple. Just wish there were more evening slots available.",
  },
  {
    id: "t3",
    name: "Fatima Sheikh",
    role: "Teacher, Coimbatore",
    photo: p(5),
    rating: 5,
    quote:
      "Had a video consultation after work and it went smoothly. The doctor did not rush and answered everything I asked. Felt like a proper in-person visit.",
  },
  {
    id: "t4",
    name: "Arjun Menon",
    role: "Business Owner, Kochi",
    photo: p(0),
    rating: 5,
    quote:
      "The doctor profiles helped me pick the right specialist. Booking to consultation, everything was hassle-free. No confusion at any step.",
  },
  {
    id: "t5",
    name: "Sneha Patel",
    role: "College Student, Ahmedabad",
    photo: p(1),
    rating: 4,
    quote:
      "Found a dermatologist nearby in just a few minutes. Clean interface and easy to navigate. Took less time than I thought it would.",
  },
  {
    id: "t6",
    name: "Rahul Verma",
    role: "Marketing Executive, Hyderabad",
    photo: p(7),
    rating: 5,
    quote:
      "Booked for my father last week. The doctor was patient, the hospital was clean and the staff were genuinely helpful. Really good experience.",
  },
  {
    id: "t7",
    name: "Nisha Kapoor",
    role: "HR Manager, Pune",
    photo: p(2),
    rating: 5,
    quote:
      "No long forms and no confusion. Just searched, booked, and visited the doctor. That kind of simplicity is exactly what I needed.",
  },
  {
    id: "t8",
    name: "Mohammed Imran",
    role: "Bank Employee, Chennai",
    photo: p(4),
    rating: 4,
    quote:
      "Good experience overall. The consultation started on time and the prescription was ready right after. The reminder before the appointment was useful too.",
  },
  {
    id: "t9",
    name: "Aditi Sharma",
    role: "Graphic Designer, Delhi",
    photo: p(8),
    rating: 5,
    quote:
      "Search filters made it easy to find a specialist close to me. Booking took less than two minutes and the waiting time at the clinic was short.",
  },
  {
    id: "t10",
    name: "Karthik Reddy",
    role: "IT Consultant, Hyderabad",
    photo: p(9),
    rating: 5,
    quote:
      "Probably the easiest healthcare app I have used. Everything feels organised and the appointment reminders actually work well. Will keep using it.",
  },
];
