export interface MedicalReport {
  id: number;
  patientId: number;
  doctorName: string;
  doctorSpecialization: string;
  reportTitle: string;
  reportType: "Lab Report" | "Prescription" | "ECG Report" | "Consultation Summary" | string;
  visitDate: string;
  hospital: string;
  diagnosis: string;
  medications?: string[];
  observations?: string[];
  recommendations?: string[];
  nextVisit?: string;
  createdAt?: string;
}

export const initialReports: MedicalReport[] = [
  {
    id: 1,
    patientId: 1,
    doctorName: "Dr. Priya Menon",
    doctorSpecialization: "Pathology & Hematology",
    reportTitle: "Complete Blood Count",
    reportType: "Lab Report",
    visitDate: "18-Jul-2026",
    hospital: "Apollo Hospitals",
    diagnosis: "Mild Anemia - Borderline Low Hemoglobin",
    observations: [
      "Hemoglobin: 11.8 g/dL (Ref: 12.0 - 15.5 g/dL)",
      "WBC Count: 6,800 /mcL (Ref: 4,500 - 11,000 /mcL)",
      "RBC Count: 4.2 Million /mcL (Ref: 4.0 - 5.2 Million)",
      "Platelet Count: 250,000 /mcL (Ref: 150,000 - 450,000 /mcL)",
      "Blood Group: O+ Positive",
    ],
    medications: [
      "Ferrous Ascorbate 100mg - Once daily after food",
      "Folic Acid 5mg - Once daily",
    ],
    recommendations: [
      "Increase dietary iron intake (spinach, beetroot, apples, pomegranate).",
      "Repeat Complete Blood Count in 4 weeks.",
      "Stay well hydrated.",
    ],
    nextVisit: "15-Aug-2026",
    createdAt: "2026-07-18T10:30:00Z",
  },
  {
    id: 2,
    patientId: 1,
    doctorName: "Dr. Rahul Sharma",
    doctorSpecialization: "Cardiology",
    reportTitle: "Prescription — Antihypertensives",
    reportType: "Prescription",
    visitDate: "10-Jul-2026",
    hospital: "Fortis Healthcare",
    diagnosis: "Stage 1 Essential Hypertension",
    observations: [
      "Blood Pressure: 138/88 mmHg",
      "Pulse Rate: 72 bpm",
      "BMI: 24.2 (Normal range)",
    ],
    medications: [
      "Telmisartan 40mg - 1 Tablet in the Morning",
      "Amlodipine 5mg - 1 Tablet at Night",
      "Hydrochlorothiazide 12.5mg - 1 Tablet in the Morning",
    ],
    recommendations: [
      "Low sodium diet (< 2g per day).",
      "Regular aerobic exercise (30 mins/day, 5 days a week).",
      "Monitor home BP readings twice weekly.",
    ],
    nextVisit: "10-Aug-2026",
    createdAt: "2026-07-10T11:15:00Z",
  },
  {
    id: 3,
    patientId: 1,
    doctorName: "Dr. Rahul Sharma",
    doctorSpecialization: "Cardiology",
    reportTitle: "ECG Report",
    reportType: "ECG Report",
    visitDate: "28-Jun-2026",
    hospital: "Fortis Healthcare",
    diagnosis: "Normal Sinus Rhythm. No acute ischemic changes.",
    observations: [
      "Heart Rate: 74 bpm",
      "Rhythm: Regular Sinus Rhythm",
      "PR Interval: 156 ms (Normal)",
      "QRS Duration: 88 ms (Normal)",
      "QT / QTc Interval: 410 / 424 ms",
      "Blood Pressure: 118/76 mmHg",
      "Oxygen Saturation (SpO2): 99% on Room Air",
    ],
    medications: [
      "Aspirin 75mg - Once daily after lunch",
      "Atorvastatin 10mg - Once daily at bedtime",
    ],
    recommendations: [
      "Continue prescribed cardiovascular medications.",
      "Maintain healthy low-cholesterol diet.",
      "Avoid smoking and heavy physical exertion.",
    ],
    nextVisit: "28-Jul-2026",
    createdAt: "2026-06-28T09:45:00Z",
  },
  {
    id: 4,
    patientId: 1,
    doctorName: "Dr. Ananya Verma",
    doctorSpecialization: "General Internal Medicine",
    reportTitle: "Consultation Summary",
    reportType: "Consultation Summary",
    visitDate: "15-Jun-2026",
    hospital: "Max Super Speciality Hospital",
    diagnosis: "Primary Hypertension - Well Controlled & General Health Evaluation",
    observations: [
      "Symptoms: Mild tension headache, fatigue for 3 days",
      "General Examination: Patient alert, oriented, afebrile",
      "Chest: Clear bilaterally, normal breath sounds",
      "Abdomen: Soft, non-tender",
    ],
    medications: [
      "Paracetamol 500mg - As needed for headache (Max 3/day)",
      "Multivitamin Supplement - Once daily with breakfast",
    ],
    recommendations: [
      "Adequate sleep (7-8 hours daily).",
      "Stress management techniques.",
      "Annual comprehensive health checkup.",
    ],
    nextVisit: "15-Sep-2026",
    createdAt: "2026-06-15T14:20:00Z",
  },
];

export function generateReportTxtContent(report: MedicalReport, patientName: string, patientIdStr: string): string {
  const lineSeparator = "----------------------------------------";
  const headerBanner = "========================================\n         HEALTHCARE+ MEDICAL REPORT\n========================================";
  const footerBanner = "========================================\nGenerated by Healthcare+\n========================================";

  let content = `${headerBanner}\n\n`;

  content += `Report Type:\n${report.reportType}\n\n`;
  content += `Patient Name:\n${patientName}\n\n`;
  content += `Patient ID:\n${patientIdStr}\n\n`;
  content += `Doctor:\n${report.doctorName}\n\n`;
  content += `Department:\n${report.doctorSpecialization}\n\n`;
  content += `Hospital:\n${report.hospital}\n\n`;
  content += `Visit Date:\n${report.visitDate}\n\n`;

  content += `${lineSeparator}\nDIAGNOSIS\n${lineSeparator}\n\n${report.diagnosis || "N/A"}\n\n`;

  if (report.observations && report.observations.length > 0) {
    content += `${lineSeparator}\nOBSERVATIONS\n${lineSeparator}\n\n`;
    report.observations.forEach((obs) => {
      content += `• ${obs}\n\n`;
    });
  }

  if (report.medications && report.medications.length > 0) {
    content += `${lineSeparator}\nPRESCRIBED MEDICATIONS\n${lineSeparator}\n\n`;
    report.medications.forEach((med) => {
      content += `• ${med}\n\n`;
    });
  }

  if (report.recommendations && report.recommendations.length > 0) {
    content += `${lineSeparator}\nRECOMMENDATIONS\n${lineSeparator}\n\n`;
    report.recommendations.forEach((rec) => {
      content += `• ${rec}\n\n`;
    });
  }

  if (report.nextVisit) {
    content += `${lineSeparator}\nNEXT FOLLOW-UP\n${lineSeparator}\n\n${report.nextVisit}\n\n`;
  }

  content += `${footerBanner}\n`;

  return content;
}

export function downloadReportAsTxt(report: MedicalReport, patientName: string, patientIdNum: number | string) {
  const patientIdFormatted = `PAT-${String(patientIdNum).padStart(6, "0")}`;
  const txtContent = generateReportTxtContent(report, patientName, patientIdFormatted);

  const cleanTitle = report.reportTitle.replace(/[^a-zA-Z0-9_\-]/g, "_");
  const fileName = `Medical_Report_${cleanTitle}.txt`;

  const blob = new Blob([txtContent], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
